languageCode = "en"
languageName = "English"
weight = 1
title = "VieRnes de Bioinformatica"
contentDir = "content/en"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Fomentar la formación y crecimiento en bioinformática a través de cursos gratuitos para toda la comunidad interesada."

[author]
name = "Jorge Alfredo Suazo Victoria"
image = "LogoAutor.png"
headline = "Genomic Science Student"
bio = "I made this web page :)"
links = [ { github = "https://github.com/3LCONEJO" } ]
